version: "3"

services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile.prod
    working_dir: /app
    volumes:
      - .:/app:ro
    dns:
      - 8.8.8.8
    environment:
      - APP_ENV=production

   composer:
    image: composer:latest
    volumes:
      - .:/app
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    command: composer install --no-progress --no-dev --optimize-autoloader 

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    volumes:
      - ./var:/app/var
      - ./public:/app/public:ro
