version: "3"

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    volumes:
      - ./var:/app/var
      - ./public:/app/public:ro
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile.prod
    working_dir: /app
    volumes:
      - .:/app:ro
    dns:
      - 8.8.8.8
    environment:
      - APP_ENV=production
    command: >
      sh -c "
        composer install --no-progress --no-dev --optimize-autoloader 
        php-fpm -F
      "
